services:
  backend:
    image: pmdc777/sitelia-backend:latest
    volumes:
      - static:/app/static
      - media:/app/media
      - db:/app
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  frontend:
    image: pmdc777/sitelia-frontend:latest
    environment:
      - NODE_ENV=production
    networks:
      - default

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/app/static
      - media:/app/media
    networks:
      - default
      - ingress-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        caddy: lia2lab.labs.unimar.br
        caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  static:
  media:
  db:

networks:
  ingress-network:
    external: true