services:
  backend:
    build: ./backend
    container_name: django-backend
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True

  frontend:
    build: ./frontend
    container_name: next-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
