services:
  backend:
    image: pmdc777/sitelia-backend:latest
    volumes:
      - static:/app/static
      - media:/app/media
      - db:/app
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    networks:
      - app-network

  frontend:
    image: pmdc777/sitelia-frontend:latest
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static
      - media:/app/media
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
      - ingress-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      labels:
        caddy: lialab.labs.unimar.br
        caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  static:
  media:
  db:

networks:
  app-network:
  ingress-network:
    external: true