services:
  backend:
    build:
      context: ./backend
    volumes:
      - static:/app/static
      - media:/app/media
      - db:/app
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:1.25.4
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/app/static
      - media:/app/media
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
      - ingress-network
    restart: always
    labels:
      caddy: lialab.labs.unimar.br
      caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  static:
  media:
  db:

networks:
  app-network:
  ingress-network:
    external: true