services:
  backend:
    build: ./backend
    container_name: django-backend
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
      - ./backend/media:/app/media
      - ./backend/db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"
    environment:
      - DEBUG=True
    networks:
      - default
      - ingress-network

  frontend:
    build: ./frontend
    container_name: next-frontend
    volumes:
      - ./frontend:/app
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - default
      - ingress-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      - frontend
      - backend
    networks:
      - default
      - ingress-network
    deploy:
      labels:
        caddy: seu-dominio.aqui.br
        caddy.reverse_proxy: "{{upstreams 80}}"
      mode: replicated
      restart_policy:
        condition: any
      replicas: 1

networks:
  default:
  ingress-network:
    external: true