services:
  backend:
    build: ./backend
    container_name: django-backend
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./backend/static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True

  frontend:
    build: ./frontend
    container_name: next-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      - frontend
      - backend
