# Generated by Django 5.1.2 on 2025-04-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('avatar', models.ImageField(blank=True, default='alunos/default_avatar.png', upload_to='alunos/')),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('avatar', models.ImageField(blank=True, default='professores/default_avatar.png', upload_to='professores/')),
                ('link', models.URLField(null=True)),
            ],
        ),
    ]
