# Generated by Django 5.1.2 on 2025-04-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='link',
            field=models.URLField(),
        ),
    ]
